name: scummvm
base: core18
adopt-info: scummvm
summary: ScummVM
description: |
    ScummVM is a program which allows you to run certain classic graphical
    point-and-click adventure games, provided you already have their data
    files. The clever part about this: ScummVM just replaces the executables
    shipped with the game, allowing you to play them on systems for which
    they were never designed!
confinement: strict
grade: stable

apps:
  scummvm:
    command: desktop-launch $SNAP/bin/scummvm
    plugs: [x11, home, pulseaudio, unity7, opengl]

parts:
  scummvm:
    after: [desktop-glib-only]
    source: https://github.com/scummvm/scummvm.git
    override-build: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      trimmed_tag="$(echo $last_committed_tag | sed 's/desc\///' | sed 's/git//' )"
      last_released_tag="$(snap info scummvm | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${trimmed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi    
      snapcraftctl build
      snapcraftctl set-version $(git -C ../src describe --tags | sed 's/desc\///' | sed 's/git//' | sed 's/^v//')
    plugin: autotools
#    To do a quick test build
#    configflags:
#      - --disable-all-engines
#      - --enable-engine=scumm
    build-packages:
      - g++
      - make
      - libsdl2-dev
      - libjpeg62-dev
      - libmpeg2-4-dev
      - libogg-dev
      - libvorbis-dev
      - libflac-dev
      - libmad0-dev
      - libpng-dev
      - libtheora-dev
      - libfaad-dev
      - libfluidsynth-dev
      - libfreetype6-dev
      - zlib1g-dev
      - libunity-dev
    stage-packages:
      - libicu60
      - libasound2
      - libfaad2
      - libflac8
      - libfluidsynth1
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libjpeg62
      - libjpeg8
      - libmad0
      - libmpeg2-4
      - libogg0
      - libpng16-16
      - libsdl2-2.0-0
      - libsndio6.1
      - libstdc++6
      - libtheora0
      - libvorbis0a
      - libvorbisfile3
      - zlib1g
      - libdbusmenu-glib4
      - libdee-1.0-4
      - libglu1-mesa
      - libslang2
      - libunity-protocol-private0
      - libunity9
      - freeglut3

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

